name: CI

on:
  push:
    branches: [dev, public]
  pull_request:
    branches: [dev, public]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - run: npm ci

      - run: npm run lint

      - run: npm run test

      - run: npx tsc --noEmit

      - run: npx prisma generate

      - run: npm run build
        env:
          DATABASE_URL: "postgresql://user:password@localhost:5432/supli?sslmode=disable"
          NEXTAUTH_SECRET: "ci-build-secret-minimum-32-characters-long"
          NEXTAUTH_URL: "http://localhost:3000"
